import { ADMIN_ROUTES } from "./admin.routes";
import { BASE_ROUTES } from "./base.routes";
import { CLIENT_ROUTES } from "./client.routes";

export const GLOBAL_ROUTES = {

    // ADMIN ROUTES
    LOGIN: `${BASE_ROUTES.ADMIN}/${ADMIN_ROUTES.LOGIN}`,
    REGISTER: `${BASE_ROUTES.ADMIN}/${ADMIN_ROUTES.REGISTER}`,

    // CLIENT ROUTES
    HOME: `${BASE_ROUTES.CLIENT}/${CLIENT_ROUTES.HOME}`,
    COURSES: `${BASE_ROUTES.CLIENT}/${CLIENT_ROUTES.COURSES}`,
    EVENTS: `${BASE_ROUTES.CLIENT}/${CLIENT_ROUTES.EVENTS}`,
    PACKS: `${BASE_ROUTES.CLIENT}/${CLIENT_ROUTES.PACKS}`
}